apiVersion: v1
kind: Service
metadata:
  name: location-finder-bcd2-service
  labels:
    app: location-finder
spec:
  type: NodePort
  selector:
    app: location-finder
  ports:
    - name: location-finder-container
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: prometheus
      protocol: TCP
      port: 9090
      targetPort: 9090